limit_req_zone $binary_remote_addr zone=backup_req_ip:1m rate=5r/s;
limit_req_zone $server_name zone=backup_fetch_all:1m rate=6r/m;
limit_req_zone $server_name zone=backup_mutation_all:1m rate=30r/m;
limit_conn_zone $binary_remote_addr zone=backup_conn_ip:1m;
limit_conn_zone $server_name zone=backup_fetch_conn_all:1m;
limit_conn_zone $server_name zone=backup_mutation_conn_all:1m;
limit_req_zone $binary_remote_addr zone=descriptor_req_ip:1m rate=5r/s;
limit_req_zone $server_name zone=descriptor_store_all:1m rate=30r/m;
limit_req_zone $server_name zone=descriptor_lookup_all:1m rate=60r/m;
limit_conn_zone $binary_remote_addr zone=descriptor_conn_ip:1m;
limit_conn_zone $server_name zone=descriptor_store_conn_all:1m;
limit_conn_zone $server_name zone=descriptor_lookup_conn_all:1m;
limit_req_zone $binary_remote_addr zone=recovery_req_ip:1m rate=32r/s;
limit_req_zone $server_name zone=recovery_fetch_all:1m rate=64r/s;
limit_req_zone $server_name zone=recovery_store_all:1m rate=32r/s;
limit_conn_zone $binary_remote_addr zone=recovery_conn_ip:1m;
limit_conn_zone $server_name zone=recovery_fetch_conn_all:1m;
limit_conn_zone $server_name zone=recovery_store_conn_all:1m;
